/* =========================================================
   PACOTE DE PERGUNTAS — CapyFi (v6, reconstruído do zero)

   Toda pergunta nasce de um fato presente em docs.capyfi.com
   (páginas: home, /comptroller, /ctokens) ou em fontes públicas
   confirmadas (app.capyfi.com, DeFiLlama, auditorias OpenZeppelin
   e Coinspect, post público do fundador da Ripio sobre o
   lançamento na Base). Nenhum cenário de terceiro foi inventado
   desta vez — toda "situação" é a própria pessoa usando uma
   função ou mecanismo que está documentado de verdade.
   ========================================================= */

const pack = {
  name: { pt: "CapyFi", en: "CapyFi" },
  questions: {
    easy: [
      { question: { pt: "A CapyFi cita o Compound Whitepaper de 2019 na própria documentação. O que isso indica sobre o protocolo?", en: "CapyFi cites the 2019 Compound Whitepaper in its own docs. What does that indicate about the protocol?" },
        answers: { pt: ["Ele é um fork da arquitetura do Compound v2", "Ele foi comprado pela empresa Compound", "Ele é só uma cópia visual do site do Compound", "Ele proíbe qualquer uso do nome Compound"],
                   en: ["It's a fork of the Compound v2 architecture", "It was bought by the Compound company", "It's just a visual copy of Compound's website", "It bans any use of the Compound name"] }, correct: 0 },
      { question: { pt: "Ao fornecer um ativo pela primeira vez na CapyFi, o que você recebe em troca?", en: "When you first supply an asset on CapyFi, what do you receive in return?" },
        answers: { pt: ["Um caToken, representando seu depósito", "Um recibo assinado digitalmente pela equipe", "Nada, o depósito só fica registrado internamente", "Um token de governança com direito a voto"],
                   en: ["A caToken, representing your deposit", "A digitally signed receipt from the team", "Nothing, the deposit is just recorded internally", "A governance token with voting rights"] }, correct: 0 },
      { question: { pt: "Ao fornecer ETH nativo na CapyFi, qual caToken você recebe?", en: "When you supply native ETH on CapyFi, which caToken do you receive?" },
        answers: { pt: ["caETH", "caWBTC", "caUSDC", "caLAC"],
                   en: ["caETH", "caWBTC", "caUSDC", "caLAC"] }, correct: 0 },
      { question: { pt: "Ao fornecer Bitcoin na CapyFi, qual caToken representa esse depósito?", en: "When you supply Bitcoin on CapyFi, which caToken represents that deposit?" },
        answers: { pt: ["caWBTC", "caUSDT", "caWLD", "caRPC"],
                   en: ["caWBTC", "caUSDT", "caWLD", "caRPC"] }, correct: 0 },
      { question: { pt: "Você quer expor sua carteira ao real via CapyFi. Qual caToken serve pra isso?", en: "You want your wallet exposed to the Brazilian real via CapyFi. Which caToken is for that?" },
        answers: { pt: ["caWBRL", "caWARS", "caUSDC", "caETH"],
                   en: ["caWBRL", "caWARS", "caUSDC", "caETH"] }, correct: 0 },
      { question: { pt: "Ao fornecer LAC na CapyFi, qual caToken você recebe?", en: "When you supply LAC on CapyFi, which caToken do you receive?" },
        answers: { pt: ["caLAC", "caWLD", "caWBRL", "caRPC"],
                   en: ["caLAC", "caWLD", "caWBRL", "caRPC"] }, correct: 0 },
      { question: { pt: "Sua caUSDC tem 8 casas decimais, mesmo o USDC original tendo só 6. Por quê?", en: "Your caUSDC has 8 decimal places, even though the original USDC only has 6. Why?" },
        answers: { pt: ["Todo caToken usa 8 decimais, é um padrão do protocolo", "É um bug antigo e conhecido que ainda será corrigido", "O caUSDC secretamente vale menos que o USDC", "Só ativos acima de 6 decimais entram na CapyFi"],
                   en: ["Every caToken uses 8 decimals, it's a protocol standard", "It's an old, known bug that will still be fixed", "caUSDC secretly is worth less than USDC", "Only assets with more than 6 decimals join CapyFi"] }, correct: 0 },
      { question: { pt: "Você quer usar seu USDC fornecido como garantia pra pedir outro ativo emprestado. Que passo falta?", en: "You want to use your supplied USDC as collateral to borrow another asset. What step is missing?" },
        answers: { pt: ["Habilitar aquele ativo (Enter Market) na sua conta", "Esperar 24 horas corridas após o primeiro depósito", "Converter o caUSDC de volta em USDC antes", "Nenhum, qualquer depósito já serve como garantia"],
                   en: ["Enabling that asset (Enter Market) on your account", "Waiting 24 straight hours after the first deposit", "Converting caUSDC back into USDC first", "None, any deposit already works as collateral"] }, correct: 0 },
      { question: { pt: "O Collateral Factor de um mercado na CapyFi determina o quê?", en: "What does a CapyFi market's Collateral Factor determine?" },
        answers: { pt: ["Quanto dá pra pedir emprestado por trás daquele colateral", "O preço de venda mínimo e garantido daquele ativo", "A ordem de exibição dos mercados na interface", "Se o ativo pode ou não ser fornecido"],
                   en: ["How much can be borrowed against that collateral", "That asset's minimum, guaranteed resale price", "The display order of markets in the interface", "Whether the asset can be supplied at all"] }, correct: 0 },
      { question: { pt: "O que representa a Account Liquidity de uma conta na CapyFi?", en: "What does a CapyFi account's Account Liquidity represent?" },
        answers: { pt: ["A folga entre o colateral e a dívida daquela conta", "O saldo total da carteira, convertido em dólares americanos", "O número de vezes que a conta já foi usada", "A taxa de juros cobrada daquela conta"],
                   en: ["The gap between that account's collateral and debt", "The wallet's total balance, converted into US dollars", "How many times the account has been used", "The interest rate charged to that account"] }, correct: 0 },
      { question: { pt: "O que acontece com uma conta cuja Account Liquidity fica negativa (shortfall)?", en: "What happens to an account whose Account Liquidity goes negative (shortfall)?" },
        answers: { pt: ["Ela fica sujeita à liquidação", "Ela é banida automaticamente da CapyFi", "Nada, o valor negativo só é cosmético", "Ela recebe um empréstimo extra pra cobrir a diferença"],
                   en: ["It becomes subject to liquidation", "It's automatically banned from CapyFi", "Nothing, the negative value is just cosmetic", "It receives an extra loan to cover the gap"] }, correct: 0 },
      { question: { pt: "Numa liquidação via LiquidateBorrow, o que quem liquida recebe?", en: "In a LiquidateBorrow liquidation, what does the liquidator receive?" },
        answers: { pt: ["O colateral do devedor, com um desconto", "Um pagamento fixo em LAC repassado direto", "Um NFT de comprovante da liquidação", "Nada, a função só registra o evento"],
                   en: ["The debtor's collateral, at a discount", "A fixed payment in LAC passed along directly", "An NFT receipt of the liquidation", "Nothing, the function only logs the event"] }, correct: 0 },
      { question: { pt: "O que o Close Factor limita numa liquidação?", en: "What does the Close Factor limit in a liquidation?" },
        answers: { pt: ["Quanto da dívida pode ser pago numa única liquidação", "Quantas vezes por dia inteiro uma conta pode ser liquidada", "O valor máximo de colateral aceito no protocolo", "O tempo que uma transação de liquidação demora"],
                   en: ["How much of the debt can be repaid in one liquidation", "How many times in a full day an account can be liquidated", "The maximum collateral value accepted by the protocol", "How long a liquidation transaction takes"] }, correct: 0 },
      { question: { pt: "Pra que serve o Liquidation Incentive?", en: "What is the Liquidation Incentive for?" },
        answers: { pt: ["Dar um bônus de colateral pra quem liquida a posição", "Cobrar uma multa extra e separada de quem foi liquidado", "Definir o preço mínimo de qualquer ativo", "Pagar a equipe da CapyFi por cada liquidação"],
                   en: ["Giving a collateral bonus to whoever liquidates the position", "Charging a separate extra fine from whoever got liquidated", "Setting the minimum price of any asset", "Paying CapyFi's team for each liquidation"] }, correct: 0 },
      { question: { pt: "Tempos depois de fornecer um ativo, por que dá pra resgatar mais do que você depositou?", en: "Some time after supplying an asset, why can you redeem more than you deposited?" },
        answers: { pt: ["A Exchange Rate do caToken sobe conforme o juro acumula", "A CapyFi soma um bônus fixo e surpresa todo santo mês", "O ativo original se valorizou no mercado", "Isso é um erro de exibição na interface"],
                   en: ["The caToken's Exchange Rate rises as interest accrues", "CapyFi adds a fixed, surprise bonus every single month", "The original asset appreciated on the market", "That's a display bug in the interface"] }, correct: 0 },
      { question: { pt: "Você quer auditar o código da CapyFi por conta própria, sem depender só da palavra da equipe. Isso é possível?", en: "You want to audit CapyFi's code yourself, without relying only on the team's word. Is that possible?" },
        answers: { pt: ["Ler e auditar o código, que é aberto", "Nada, o código-fonte nunca foi publicado", "Só mediante assinatura de acordo de sigilo", "Só se você for um parceiro institucional"],
                   en: ["Reading and auditing the code, which is open", "Nothing, the source code was never published", "Only after signing a non-disclosure agreement", "Only if you're an institutional partner"] }, correct: 0 },
      { question: { pt: "Quais empresas de auditoria revisaram a segurança da CapyFi?", en: "Which audit firms reviewed CapyFi's security?" },
        answers: { pt: ["OpenZeppelin e Coinspect", "A Receita Federal e o Banco Central", "Uma seguradora de veículos e um cartório", "Nenhuma, o protocolo nunca foi auditado"],
                   en: ["OpenZeppelin and Coinspect", "A tax agency and a central bank", "A car insurer and a notary office", "None, the protocol was never audited"] }, correct: 0 },
      { question: { pt: "Em quais redes a CapyFi está implantada hoje?", en: "Which networks is CapyFi actually deployed on today?" },
        answers: { pt: ["Várias redes, incluindo Ethereum, Base e LaChain", "Só a LaChain, de forma exclusiva e permanente", "Só a Ethereum, sem nenhuma expansão", "Só em ambiente de teste, ainda não é público"],
                   en: ["Several networks, including Ethereum, Base, and LaChain", "Only LaChain, exclusively and permanently", "Only Ethereum, with no expansion", "Only a test environment, not public yet"] }, correct: 0 },
      { question: { pt: "Quem fica com a custódia dos fundos que você deposita na CapyFi?", en: "Who holds custody of the funds you deposit on CapyFi?" },
        answers: { pt: ["Ninguém além de você mesmo, via contrato inteligente", "A própria equipe da CapyFi guarda tudo de forma centralizada", "Um banco parceiro listado nos termos de uso", "Um fundo de investimento terceirizado"],
                   en: ["No one but you, via the smart contract", "CapyFi's own team holds it all in a centralized way", "A partner bank listed in the terms of service", "An outsourced investment fund"] }, correct: 0 },
      { question: { pt: "A CapyFi tem componentes como Comptroller, Price Feed e Whitelist, além dos caTokens. O que isso indica sobre a arquitetura?", en: "CapyFi has components like Comptroller, Price Feed, and Whitelist, besides caTokens. What does that indicate about the architecture?" },
        answers: { pt: ["Ele é dividido em módulos com responsabilidades separadas", "Ele é um único contrato monolítico, sem nenhuma divisão", "Esses nomes são só apelidos sem função real", "Cada nome representa uma blockchain diferente"],
                   en: ["It's split into modules with separate responsibilities", "It's a single monolithic contract, with no division at all", "Those names are just nicknames with no real function", "Each name represents a different blockchain"] }, correct: 0 }
    ],
    medium: [
      { question: { pt: "Qual fórmula calcula quanto seu caToken vale hoje em relação ao ativo original?", en: "Which formula calculates what your caToken is worth today relative to the original asset?" },
        answers: { pt: ["(caixa + total emprestado - reservas) dividido pelo supply total", "Preço de mercado atual do ativo dividido pelo supply total emitido", "Uma taxa fixa definida no momento do lançamento", "Total emprestado multiplicado pelo Close Factor"],
                   en: ["(cash + total borrows - reserves) divided by total supply", "The asset's current market price divided by the total issued supply", "A fixed rate set at the moment of launch", "Total borrows multiplied by the Close Factor"] }, correct: 0 },
      { question: { pt: "O Reserve Factor separa parte dos juros de quem pede emprestado. Pra onde vai essa parte?", en: "The Reserve Factor sets aside part of borrowers' interest. Where does that portion go?" },
        answers: { pt: ["Vira reserva acumulada do próprio protocolo", "É distribuída em partes iguais entre todos os usuários", "É enviada direto pra carteira dos fundadores", "É queimada e sai de circulação"],
                   en: ["It becomes the protocol's own accumulated reserve", "It's distributed equally among all users", "It's sent directly to the founders' wallet", "It's burned and leaves circulation"] }, correct: 0 },
      { question: { pt: "De quais valores deriva a Supply Rate de um mercado, o quanto quem fornece ganha?", en: "What values does a market's Supply Rate, how much suppliers earn, derive from?" },
        answers: { pt: ["Da taxa de empréstimo daquele mercado e do Reserve Factor", "Só do preço de mercado do LAC naquele exato momento", "De um número fixo definido manualmente pela equipe", "Da quantidade de usuários cadastrados no protocolo"],
                   en: ["That market's borrow rate and the Reserve Factor", "Only LAC's market price at that exact moment", "A fixed number manually set by the team", "The number of users registered on the protocol"] }, correct: 0 },
      { question: { pt: "Qual é a diferença entre os dois tipos de caToken, CErc20 e CEther?", en: "What's the difference between the two caToken types, CErc20 and CEther?" },
        answers: { pt: ["CErc20 lida com tokens ERC-20, CEther lida com Ether nativo", "CErc20 só existe em ambiente de teste, nunca em produção", "CEther nunca acumula rendimento com o tempo", "Não existe diferença real, são nomes alternativos"],
                   en: ["CErc20 handles ERC-20 tokens, CEther handles native Ether", "CErc20 only exists in a test environment, never in production", "CEther never accrues yield over time", "There's no real difference, they're alternate names"] }, correct: 0 },
      { question: { pt: "Você quer resgatar entregando uma quantidade exata de caTokens, não um valor específico do ativo. Qual função usar?", en: "You want to redeem by handing over an exact caToken amount, not a specific asset value. Which function do you use?" },
        answers: { pt: ["Redeem", "RedeemUnderlying", "Transfer", "Approve"],
                   en: ["Redeem", "RedeemUnderlying", "Transfer", "Approve"] }, correct: 0 },
      { question: { pt: "Você quer sacar exatamente 100 USDC, nem mais nem menos. Redeem ou RedeemUnderlying?", en: "You want to withdraw exactly 100 USDC, no more, no less. Redeem or RedeemUnderlying?" },
        answers: { pt: ["RedeemUnderlying", "Redeem", "Mint", "Borrow"],
                   en: ["RedeemUnderlying", "Redeem", "Mint", "Borrow"] }, correct: 0 },
      { question: { pt: "O que deveria acontecer se você tentasse pedir emprestado mais do que sua Account Liquidity permite?", en: "What should happen if you tried to borrow more than your Account Liquidity allows?" },
        answers: { pt: ["A transação de Borrow deveria falhar", "O empréstimo é liberado normalmente mesmo assim", "Seu colateral é automaticamente aumentado", "A CapyFi te avisa mas libera do mesmo jeito"],
                   en: ["The Borrow transaction should fail", "The loan is released normally anyway", "Your collateral is automatically increased", "CapyFi warns you but releases it anyway"] }, correct: 0 },
      { question: { pt: "Você quer pagar sua própria dívida na CapyFi de volta ao protocolo. Qual função usar?", en: "You want to repay your own CapyFi debt back to the protocol. Which function do you use?" },
        answers: { pt: ["RepayBorrow", "RepayBorrowBehalf", "LiquidateBorrow", "Redeem"],
                   en: ["RepayBorrow", "RepayBorrowBehalf", "LiquidateBorrow", "Redeem"] }, correct: 0 },
      { question: { pt: "Você quer pagar a dívida de outra pessoa, não a sua. Existe uma função separada pra esse caso?", en: "You want to repay someone else's debt, not your own. Is there a separate function for that case?" },
        answers: { pt: ["RepayBorrowBehalf", "RepayBorrow", "Transfer", "Mint"],
                   en: ["RepayBorrowBehalf", "RepayBorrow", "Transfer", "Mint"] }, correct: 0 },
      { question: { pt: "Qual função mostra quanto de um ativo está disponível pra saque imediato num mercado, sem contar o que já foi emprestado?", en: "Which function shows how much of an asset is available for immediate withdrawal in a market, not counting what's already borrowed?" },
        answers: { pt: ["getCash()", "totalSupply()", "totalBorrows()", "exchangeRate()"],
                   en: ["getCash()", "totalSupply()", "totalBorrows()", "exchangeRate()"] }, correct: 0 },
      { question: { pt: "Além de fornecer e pedir emprestado, a CapyFi tem seções chamadas Vaults e Rewards. O que são?", en: "Besides supplying and borrowing, CapyFi has sections called Vaults and Rewards. What are they?" },
        answers: { pt: ["Funcionalidades do protocolo além do lending principal", "A única forma real e possível de usar a CapyFi", "Um substituto direto pro Comptroller", "Uma segunda blockchain rodando à parte"],
                   en: ["Protocol features beyond the core lending", "The only real and possible way to use CapyFi", "A direct substitute for the Comptroller", "A second blockchain running separately"] }, correct: 0 },
      { question: { pt: "De onde vem o preço usado pra calcular se sua conta pode ser liquidada?", en: "Where does the price used to calculate whether your account can be liquidated come from?" },
        answers: { pt: ["Price Feed", "Whitelist", "CompoundLens", "Maximillion"],
                   en: ["Price Feed", "Whitelist", "CompoundLens", "Maximillion"] }, correct: 0 },
      { question: { pt: "A CapyFi lista um componente chamado CompoundLens, separado do Comptroller. O que ele provavelmente agrega?", en: "CapyFi lists a component called CompoundLens, separate from the Comptroller. What does it likely aggregate?" },
        answers: { pt: ["Dados de leitura de vários mercados numa única consulta", "As regras completas de liquidação de cada mercado individual", "O código-fonte completo do protocolo", "A lista de auditorias já realizadas"],
                   en: ["Read-only data from several markets in a single query", "Each individual market's complete liquidation rules", "The protocol's complete source code", "The list of audits already performed"] }, correct: 0 },
      { question: { pt: "Existe um componente chamado Maximillion na CapyFi, ao lado do Comptroller e do Price Feed. O que isso sugere sobre sua função?", en: "CapyFi has a component called Maximillion, alongside the Comptroller and Price Feed. What does that suggest about its role?" },
        answers: { pt: ["É uma função auxiliar específica, não o núcleo do protocolo", "É o nome interno oficial e exclusivo do token de governança", "É a blockchain onde a CapyFi roda por padrão", "É o nome comercial completo da empresa CapyFi"],
                   en: ["It's a specific helper function, not the protocol's core", "It's the governance token's official, exclusive internal name", "It's the blockchain CapyFi runs on by default", "It's CapyFi the company's full commercial name"] }, correct: 0 },
      { question: { pt: "Sua posição de USDC na Base não muda quando você deposita USDC na LaChain. Por quê?", en: "Your USDC position on Base doesn't change when you deposit USDC on LaChain. Why?" },
        answers: { pt: ["Cada rede roda um mercado separado, sem liquidez compartilhada", "É um bug antigo e conhecido que a equipe ainda vai corrigir", "As duas redes sincronizam o saldo automaticamente", "Só uma das implantações está realmente ativa"],
                   en: ["Each network runs a separate market, with no shared liquidity", "It's an old, known bug the team will still fix", "The two networks sync balances automatically", "Only one of the deployments is actually active"] }, correct: 0 },
      { question: { pt: "A CapyFi lista eficiência de gas melhorada como característica do fork. O que isso significa na prática?", en: "CapyFi lists improved gas efficiency as a feature of the fork. What does that mean in practice?" },
        answers: { pt: ["Transações custam menos gas do que na versão original", "O gas é totalmente eliminado em toda e qualquer transação", "A CapyFi paga o gas de todo mundo automaticamente", "O gas só existe na rede Ethereum, não nas outras"],
                   en: ["Transactions cost less gas than the original version", "Gas is fully eliminated on absolutely every transaction", "CapyFi automatically pays everyone's gas", "Gas only exists on Ethereum, not the other networks"] }, correct: 0 },
      { question: { pt: "O que caWARS e caWBRL têm em comum?", en: "What do caWARS and caWBRL have in common?" },
        answers: { pt: ["São versões tokenizadas de moedas latino-americanas", "São as duas únicas stablecoins do mundo atreladas ao dólar", "São tokens exclusivos da rede Ethereum", "São nomes alternativos pro mesmo token LAC"],
                   en: ["They're tokenized versions of Latin American currencies", "They're the only two dollar-pegged stablecoins in the world", "They're tokens exclusive to the Ethereum network", "They're alternate names for the same LAC token"] }, correct: 0 },
      { question: { pt: "caWLD também está na lista de mercados da CapyFi. Dado que WLD é o token do World Chain, o que isso confirma?", en: "caWLD is also in CapyFi's market list. Given WLD is World Chain's token, what does that confirm?" },
        answers: { pt: ["Ela também está implantada na rede World Chain", "Ela comprou uma participação no projeto Worldcoin", "Ela migrou definitivamente da LaChain pro World Chain", "Ela usa WLD só como unidade interna de cálculo"],
                   en: ["It's also deployed on the World Chain network", "It bought a stake in the Worldcoin project", "It permanently migrated from LaChain to World Chain", "It only uses WLD as an internal unit of calculation"] }, correct: 0 },
      { question: { pt: "Dá pra confiar cegamente no preço que o Price Feed devolve, sem checagem nenhuma a mais?", en: "Can you blindly trust the price the Price Feed returns, with no extra check at all?" },
        answers: { pt: ["Um preço errado do oráculo pode liquidar contas injustamente", "Nenhum risco, o Price Feed é sempre matematicamente infalível", "O risco existe só na teoria, nunca na prática", "O Comptroller ignora esse preço por padrão"],
                   en: ["A wrong oracle price can unfairly liquidate accounts", "No risk at all, the Price Feed is always mathematically infallible", "The risk only exists in theory, never in practice", "The Comptroller ignores that price by default"] }, correct: 0 },
      { question: { pt: "Por que cada mercado da CapyFi tem seu próprio Collateral Factor, em vez de um valor único pra todos?", en: "Why does each CapyFi market have its own Collateral Factor, instead of one value for all?" },
        answers: { pt: ["Cada ativo tem um perfil de risco e liquidez diferente", "É só uma escolha estética da interface", "Ativos mais antigos sempre recebem o valor mais alto", "O valor é sorteado aleatoriamente na criação do mercado"],
                   en: ["Each asset has a different risk and liquidity profile", "It's just an aesthetic interface choice", "Older assets always get the highest value", "The value is randomly drawn when the market is created"] }, correct: 0 }
    ],
    hard: [
      { question: { pt: "A CapyFi descreve seu desenvolvimento como community-driven. O que isso sugere sobre como o protocolo evolui?", en: "CapyFi describes its development as community-driven. What does that suggest about how the protocol evolves?" },
        answers: { pt: ["Pode incorporar sugestões e contribuições externas ao código", "Só a equipe original tem permissão de sugerir qualquer mudança", "O código nunca pode ser modificado por ninguém depois do lançamento", "A comunidade vota sozinha, sem nenhuma revisão técnica"],
                   en: ["It can incorporate external suggestions and code contributions", "Only the original team is allowed to suggest any change", "The code can never be modified by anyone after launch", "The community votes alone, with no technical review"] }, correct: 0 },
      { question: { pt: "caRPC está na lista de mercados da CapyFi, ao lado de caLAC e caWLD. Dado que a Ripio criou a LaChain, o que é razoável supor sobre RPC?", en: "caRPC is in CapyFi's market list, alongside caLAC and caWLD. Given Ripio created LaChain, what's reasonable to assume about RPC?" },
        answers: { pt: ["É provavelmente um token ligado ao ecossistema da Ripio", "É certamente o nome interno do Bitcoin na CapyFi", "É o mesmo ativo que o USDC, só com sigla diferente", "Não tem relação nenhuma com o resto da lista de mercados"],
                   en: ["It's likely a token tied to Ripio's own ecosystem", "It's certainly Bitcoin's internal name on CapyFi", "It's the same asset as USDC, just with a different ticker", "It has no relation at all to the rest of the market list"] }, correct: 0 },
      { question: { pt: "Um contrato de caToken mostra valores como 1000000000000000000 representando a unidade 1. Que sistema matemático é esse?", en: "A caToken contract shows values like 1000000000000000000 representing the unit 1. What math system is that?" },
        answers: { pt: ["Matemática exponencial com mantissa escalada por 10^18", "Notação científica nativa e padrão da linguagem Solidity", "Um erro de arredondamento propagado do Compound", "Um sistema de contagem em base 16"],
                   en: ["Exponential math with a mantissa scaled by 10^18", "The Solidity language's native, standard scientific notation", "A rounding error inherited from Compound", "A base-16 counting system"] }, correct: 0 },
      { question: { pt: "Você tem três empréstimos abertos ao mesmo tempo e fica sujeito à liquidação. Como o Close Factor se aplica?", en: "You have three open loans at once and become liquidatable. How does the Close Factor apply here?" },
        answers: { pt: ["Se aplica a um ativo emprestado por vez, não à soma", "Se aplica de uma vez só à soma total das três dívidas", "Cancela automaticamente dois dos três empréstimos", "Deixa de valer quando há mais de uma dívida aberta"],
                   en: ["It applies to one borrowed asset at a time, not the sum", "It applies all at once to the total sum of all three debts", "It automatically cancels two of the three loans", "It stops applying when there's more than one open debt"] }, correct: 0 },
      { question: { pt: "Um ativo é listado com Collateral Factor de 0%. O que ainda dá pra fazer com ele?", en: "An asset is listed with a 0% Collateral Factor. What can still be done with it?" },
        answers: { pt: ["Ainda dá pra fornecer e pedir emprestado, só não usar como garantia", "Nada, o ativo fica completamente bloqueado pra qualquer uso", "Ele automaticamente vira garantia obrigatória", "Ele é removido da lista de mercados"],
                   en: ["It can still be supplied and borrowed, just not used as collateral", "Nothing, the asset is fully blocked for any use at all", "It automatically becomes mandatory collateral", "It gets removed from the market list"] }, correct: 0 },
      { question: { pt: "Como o Comptroller decide, na hora da checagem, se uma conta já pode ser liquidada?", en: "How does the Comptroller decide, at the moment of checking, whether an account can already be liquidated?" },
        answers: { pt: ["Se o shortfall da Account Liquidity é maior que zero", "Se a conta já foi liquidada alguma vez desde a criação", "Se o dono da conta está numa lista negra manual", "Se passaram mais de 30 dias desde o empréstimo"],
                   en: ["Whether the Account Liquidity shortfall is greater than zero", "Whether the account has ever been liquidated since creation", "Whether the account owner is on a manual blocklist", "Whether more than 30 days have passed since the loan"] }, correct: 0 },
      { question: { pt: "Auditorias como as da OpenZeppelin e da Coinspect garantem segurança absoluta pra CapyFi?", en: "Do audits like OpenZeppelin's and Coinspect's guarantee absolute security for CapyFi?" },
        answers: { pt: ["Reduz, mas não elimina, o risco de falhas ainda não encontradas", "Garante segurança cem por cento contra qualquer ataque", "Significa que nenhum código novo precisa de revisão futura", "Prova matematicamente que o contrato nunca falhará"],
                   en: ["It reduces, but doesn't eliminate, the risk of undiscovered flaws", "It guarantees one hundred percent security against any attack", "It means no new code ever needs future review", "It mathematically proves the contract will never fail"] }, correct: 0 },
      { question: { pt: "Por que reaproveitar a arquitetura do Compound v2, em vez de escrever tudo do zero, é uma vantagem técnica?", en: "Why is reusing Compound v2's architecture, instead of writing everything from scratch, a technical advantage?" },
        answers: { pt: ["Reaproveita lógica já testada em produção por outro protocolo", "Porque escrever qualquer código novo é sempre proibido por lei", "Porque o Compound paga a CapyFi por usar seu nome", "Porque não existe nenhuma outra arquitetura disponível"],
                   en: ["It reuses logic already tested in production by another protocol", "Because writing any new code is always legally prohibited", "Because Compound pays CapyFi to use its name", "Because no other architecture is available"] }, correct: 0 },
      { question: { pt: "Você tenta interagir com um mercado que não existe na CapyFi. Que tipo de erro deveria aparecer?", en: "You try to interact with a market that doesn't exist on CapyFi. What kind of error should show up?" },
        answers: { pt: ["Um erro indicando que aquele mercado não foi habilitado", "Um erro genérico de saldo insuficiente", "Um erro de rede congestionada", "Nenhum erro, a transação seria só ignorada"],
                   en: ["An error indicating that market wasn't enabled", "A generic insufficient balance error", "A network congestion error", "No error, the transaction would just be ignored"] }, correct: 0 },
      { question: { pt: "Além de gerar receita, que função de segurança o Reserve Factor cumpre?", en: "Beyond generating revenue, what safety function does the Reserve Factor serve?" },
        answers: { pt: ["Funciona como um colchão financeiro em cenários de perda", "Define sozinho o preço de emissão de novos caTokens", "Substitui a necessidade de qualquer colateral", "Controla quantos usuários podem se cadastrar por dia"],
                   en: ["It works as a financial buffer in loss scenarios", "It alone sets the issuance price of new caTokens", "It replaces the need for any collateral", "It controls how many users can register per day"] }, correct: 0 },
      { question: { pt: "caTokens seguem o padrão ERC-20, além de representar depósitos. O que isso permite fazer com eles, além de resgatar?", en: "caTokens follow the ERC-20 standard, besides representing deposits. What does that let you do with them, beyond redeeming?" },
        answers: { pt: ["Transferir pra outra carteira usando a função Transfer padrão", "Nada além de resgatar, o padrão ERC-20 é só decorativo", "Só a equipe da CapyFi pode movê-los entre contas", "Convertê-los automaticamente em qualquer outro caToken"],
                   en: ["Transfer them to another wallet using the standard Transfer function", "Nothing beyond redeeming, the ERC-20 standard is just decorative", "Only CapyFi's team can move them between accounts", "Automatically convert them into any other caToken"] }, correct: 0 },
      { question: { pt: "Por que a Exchange Rate de caUSDC e caETH não têm motivo pra ser iguais num mesmo instante?", en: "Why is there no reason for caUSDC and caETH's Exchange Rate to be equal at the same moment?" },
        answers: { pt: ["Cada mercado tem seu próprio caixa, total emprestado e reservas", "A fórmula da Exchange Rate é sempre a mesma constante fixa e imutável", "Só existe uma Exchange Rate global compartilhada", "É um bug quando os valores de dois mercados diferem"],
                   en: ["Each market has its own cash, total borrows, and reserves", "The Exchange Rate formula is always the same fixed, immutable constant", "There's only one shared global Exchange Rate", "It's a bug when two markets' values differ"] }, correct: 0 },
      { question: { pt: "Qual é o papel prático da Whitelist, um dos componentes centrais da CapyFi ao lado do Comptroller?", en: "What is the practical role of the Whitelist, one of CapyFi's core components alongside the Comptroller?" },
        answers: { pt: ["Quais endereços ou ativos têm permissão de acesso a algo", "O preço de mercado atualizado de cada ativo", "O cálculo da Exchange Rate de cada caToken", "A lista de auditorias já publicadas"],
                   en: ["Which addresses or assets have permission to access something", "Each asset's updated market price", "Each caToken's Exchange Rate calculation", "The list of already published audits"] }, correct: 0 },
      { question: { pt: "Como desenvolvedor, você precisa saber a qualquer momento se uma conta pode ser liquidada. Qual dado do Comptroller consultar?", en: "As a developer, you need to know at any moment whether an account can be liquidated. Which Comptroller data do you query?" },
        answers: { pt: ["O shortfall da Account Liquidity daquela conta", "O número total de transações já feitas pela conta", "A data de criação da carteira", "O saldo de LAC daquela conta especificamente"],
                   en: ["That account's Account Liquidity shortfall", "The total number of transactions the account has ever made", "The wallet's creation date", "That account's specific LAC balance"] }, correct: 0 },
      { question: { pt: "Por que a CapyFi, mesmo sendo um fork, precisou de auditoria própria em vez de confiar só na do Compound original?", en: "Why did CapyFi, even being a fork, need its own audit instead of just relying on the original Compound's audits?" },
        answers: { pt: ["Qualquer mudança no código exige nova revisão de segurança", "Auditorias de outro protocolo cobrem automaticamente qualquer fork", "Forks nunca precisam de auditoria por definição legal", "A CapyFi só usou o nome, sem herdar nenhum código real"],
                   en: ["Any code change requires a new security review", "Another protocol's audits automatically cover any fork", "Forks never need an audit by legal definition", "CapyFi only used the name, without inheriting any real code"] }, correct: 0 },
      { question: { pt: "Uma interface de terceiro tenta um Borrow acima da sua Account Liquidity, sem checar antes. O que o contrato deveria fazer mesmo assim?", en: "A third-party interface attempts a Borrow above your Account Liquidity, without checking first. What should the contract do anyway?" },
        answers: { pt: ["Reverter a transação no próprio contrato, independente da interface", "Confiar cegamente na interface e liberar o valor de qualquer jeito", "Emprestar só metade do valor pedido automaticamente", "Pausar a conta até um humano revisar manualmente"],
                   en: ["Revert the transaction in the contract itself, regardless of the interface", "Blindly trust the interface and release the amount either way", "Automatically lend only half the requested amount", "Pause the account until a human manually reviews it"] }, correct: 0 },
      { question: { pt: "caLAC e caWLD representam tokens nativos de duas redes diferentes onde a CapyFi está. O que isso sugere sobre a lista de caTokens?", en: "caLAC and caWLD represent native tokens of two different networks where CapyFi is deployed. What does that suggest about the caToken list?" },
        answers: { pt: ["Inclui ativos relevantes específicos de cada rede implantada", "É idêntica e fixa em todas as redes, sem exceção", "Só inclui tokens que também existem na Ethereum", "É decidida por votação pública a cada trimestre"],
                   en: ["It includes assets specifically relevant to each deployed network", "It's identical and fixed across every network, no exceptions", "It only includes tokens that also exist on Ethereum", "It's decided by public vote every quarter"] }, correct: 0 },
      { question: { pt: "A documentação trata a LaChain como a única rede onde a CapyFi funciona?", en: "Do CapyFi's docs treat LaChain as the only network the protocol runs on?" },
        answers: { pt: ["A LaChain aparece como uma das redes, não a única", "A documentação não menciona a LaChain em nenhum lugar", "A LaChain é citada como a rede exclusiva do protocolo", "A CapyFi abandonou totalmente a LaChain recentemente"],
                   en: ["LaChain appears as one of the networks, not the only one", "The documentation doesn't mention LaChain anywhere", "LaChain is cited as the protocol's exclusive network", "CapyFi has completely abandoned LaChain recently"] }, correct: 0 },
      { question: { pt: "O que caracteriza tecnicamente a CapyFi como não-custodial?", en: "What technically characterizes CapyFi as non-custodial?" },
        answers: { pt: ["Nenhum terceiro guarda ou controla as chaves dos fundos do usuário", "A CapyFi promete por contrato nunca perder dinheiro do usuário", "Os fundos ficam guardados numa conta bancária em nome do usuário", "O termo só se aplica a quem usa carteira de hardware"],
                   en: ["No third party holds or controls the user's fund keys", "CapyFi contractually promises to never lose user money", "Funds are held in a bank account under the user's name", "The term only applies to those using a hardware wallet"] }, correct: 0 },
      { question: { pt: "Por que forks auditados de protocolos famosos tendem a inspirar mais confiança inicial que protocolos totalmente novos?", en: "Why do audited forks of famous protocols tend to inspire more initial trust than brand-new, untested protocols?" },
        answers: { pt: ["A lógica de risco já foi validada em produção por outro projeto", "Forks são sempre proibidos por lei em absolutamente qualquer jurisdição", "Protocolos novos nunca podem ser auditados por definição", "Não existe diferença real de confiança entre os dois casos"],
                   en: ["The risk logic was already validated in production by another project", "Forks are always illegal in absolutely every jurisdiction", "Brand-new protocols can never be audited by definition", "There's no real difference in trust between the two cases"] }, correct: 0 }
    ]
  }
};

export default pack;
